# Test your FastAPI endpoints

GET http://127.0.0.1:8000/transcribe?chinese=天子（皇帝）之自稱詞，第一人稱。與「吾」「余（予）」「孤」「寡人」等語相同，於古代時不分貴賤，以第一人稱「我」使用之避棄。因伴隨為統一天下第一人之秦朝始皇帝開始使用「皇帝」一詞，亦訂定「朕」為僅皇帝一人使用之至高自稱詞，演變為其他之人禁止使用。秦朝亡後，後繼之漢王朝亦沿用「朕」為皇帝專屬之第一人稱自稱詞，故於部份著文書中皇帝出現於文中之時皆使用此字。
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
